name: Create Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag name (e.g., v0.1.0)'
        required: true
        type: string
      name:
        description: 'Release title (defaults to tag if empty)'
        required: false
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        default: false
        type: boolean

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name: ${{ inputs.name || inputs.tag }}
          target_commitish: main
          generate_release_notes: true
          draft: false
          prerelease: ${{ inputs.prerelease }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

